### ISSUE TITLE
How to open 16 channels.

### ISSUE THREAD

**Issue by foriero** [billthefarmer/mididriver#19]
Hello, may I have a question how to open 16 channels 44100Hz? 

Right now i see the code is just taking out info from sonivox but how to set it? 

Thanks you, Marek.

**Comment by billthefarmer** [comment]
I'm not sure what you are asking. There are a few relevant points:
The Sonivox midi synthesizer is part of Android and built in to each device. You can't change it unless you get the sources and build a new version to include in your app. My driver just provides access to it.
The number of channels and sample rate are fixed in the code.

If you mean midi channels, see https://github.com/billthefarmer/mididriver/issues/18.
